# Generated by Django 4.2.1 on 2023-07-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cold_groceries_ice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.IntegerField()),
                ('billtotal', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('pdf', models.FileField(upload_to='static/bills')),
            ],
        ),
        migrations.AddField(
            model_name='cold',
            name='itemprice',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cosmetic',
            name='itemprice',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='groceries',
            name='itemprice',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ice',
            name='itemprice',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cold',
            name='itemid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cosmetic',
            name='itemid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='groceries',
            name='itemid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ice',
            name='itemid',
            field=models.CharField(max_length=100),
        ),
    ]
