# Generated by Django 4.2.1 on 2023-07-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_billno_generatedbills_cold_itemprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('add', models.CharField(max_length=100)),
                ('call', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Billno',
        ),
        migrations.DeleteModel(
            name='GeneratedBills',
        ),
    ]
