# Generated by Django 4.2.1 on 2023-07-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_seller_delete_billno_delete_generatedbills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='call',
            field=models.CharField(max_length=10),
        ),
    ]
