# Generated by Django 4.2.1 on 2023-07-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_seller_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namebuyer', models.CharField(max_length=100)),
                ('addbuyer', models.CharField(max_length=100)),
                ('callbuyer', models.CharField(max_length=10)),
            ],
        ),
    ]
